### ISSUE TITLE
datadog_role has permanent changes on a permission

### ISSUE THREAD

**Issue by BastienM** [DataDog/terraform-provider-datadog#1507]
### Terraform Version

```
⇒ terraform --version
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.

⇒ terraform providers

Providers required by configuration:
.
└── provider[registry.terraform.io/datadog/datadog] 3.14.0

Providers required by state:

    provider[registry.terraform.io/datadog/datadog]
```

### Affected Resource(s)

- `datadog_role`

### Terraform Configuration Files

```hcl
provider "datadog" {
  api_url = "https://api.datadoghq.eu"
}

locals {
  config = yamldecode(join("\n", [for f in fileset("config", "*.yaml") : file("config/${f}")]))
}

resource "datadog_role" "main" {
  for_each = { for k, v in local.config.rbac.roles : v.name => v.permissions }
 
  name = each.key
 
  dynamic "permission" {
    for_each = each.value
 
    content {
      id = lookup(local.config.rbac.permissions, permission.value, null)
    }
  }
}
```

And the YAML config file
```yaml
rbac:
  # Extracted from 'data.datadog_permissions'
  permissions:
    # yamllint disable rule:line-length
    admin: "f1624684-d87d-11e8-acac-efb4dbffab1c"
    [...]
    data_scanner_read: "b39da144-90af-11eb-9428-da7ad0900005"
    data_scanner_write: "b39fb79a-90af-11eb-9428-da7ad0900005"
    [...]
    user_app_keys: "046682c4-ec5c-11ea-9483-2727954feb30"
    # yamllint enable rule:line-length

  roles:
    - name: "Core Platform"
      sso_mapping:
        key: "Member-of"
        value: "core-platform"
      permissions:
        - admin
        [...]
        - debugger_read
        - debugger_write
        [...]
        - user_app_keys

    - name: "AppSec"
      sso_mapping: {}
      permissions:
        - admin
        [...]
        - debugger_read
        - generate_dashboard_reports
       [...]
        - user_app_keys

    - name: "Developer"
      sso_mapping: {}
      permissions:
        - apm_pipelines_read
       [...]
        - debugger_read
       [...]
        - user_app_keys
```

### Debug Output

- https://gist.github.com/BastienM/70a21f2f65ccdabc5e6e14c49b6615f4

### Expected Behavior

Once applied, Terraform should not detect the changes any more.

### Actual Behavior

Terraform detect a permanent change on `debugger_read` for only two custom roles on three.
The other one has `debugger_read` and `debugger_write` and don't have this issue.

### Steps to Reproduce

1. Create a new `datadog_role` with `debugger_read` and/or `debugger_write`
2. `terraform apply`
3. `terraform plan`
4. The changes are still detected

### Important Factoids

This issue arose today, I was playing the same resource yesterday and `debugger_read` and `debugger_write` were not part of the available permissions.

So there is a 50/50 chance that this a pure API issue rather than one coming from the provider.
